-- :checkhealth nvim-treesitter
-- :TSInstall c lua markdown markdown_inline query vim vimdoc
return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      sync_install = false,
      auto_install = true,
      highlight = {
        enable = true,
      },
      ensure_installed = {
        "bash",
        "c",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "git_config",
        "gitignore",
        "go",
        "golang",
        "gomod",
        "gotmpl",
        "gpg",
        "help",
        "html",
        "htmldjango",
        "javascript",
        "jinja",
        "jinja_inline",
        "jq",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "nginx",
        "perl",
        "pod",
        "python",
        "regex",
        "rust",
        "scss",
        "sql",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "zig",
      },
    },
  },
}
